---
title: "Identifying the impacts of extreme weather"
author: Aakriti Poudel
date: "10/08/2025"
format: pdf
#output
  #html: default
code-fold: FALSE
editor: visual
execute: 
  warning: false
  message: false
---

## Load libraries

```{r}
library(tidyverse)
library(sf)
library(tmap)
library(spData)
library(terra)
library(kableExtra)
library(ggplot2)
library(spDataLarge)
library(geodata)
library(stars)
```

## Read data

```{r}
#| output: false
#| warning: false
#| message: false

# Read data for night lights
tile05_07 <- read_stars(here::here('data', 'VNP46A1', 'VNP46A1.A2021038.h08v05.001.2021039064328.tif'))
tile06_07 <- read_stars(here::here('data', 'VNP46A1', 'VNP46A1.A2021038.h08v06.001.2021039064329.tif'))
tile05_16 <- read_stars(here::here('data', 'VNP46A1', 'VNP46A1.A2021047.h08v05.001.2021048091106.tif'))
tile06_16 <- read_stars(here::here('data', 'VNP46A1', 'VNP46A1.A2021047.h08v06.001.2021048091105.tif'))
```

```{r}
#| include: false
st_crs(tile05_07)
```

## Data wrangling

**Produce a set of maps comparing night light intensities before and after the first two storms.**

### Merge raster data

```{r}
# Merge two raster data of February 7
nightlight_07 <- st_mosaic(tile05_07, tile06_07)

# Merge two raster data of February 16
nightlight_16 <- st_mosaic(tile05_16, tile06_16)
```

```{r}
# Create Houston bounding box
houston_bbox <- st_bbox(c(xmin = -96.5, xmax = -94.5, ymin = 29, ymax = 30.5),
                        crs = 'EPSG:4326')

# Convert bbox to polygon for cropping
#houston <- st_as_sfc(houston_bbox)

# Crop all three raster data to Houston area
nightlight_07_crop <- st_crop(nightlight_07, houston_bbox)
nightlight_16_crop <- st_crop(nightlight_16, houston_bbox)
```

```{r}
# Map for February 7 (before storm)
beforestorm <- tm_shape(nightlight_07_crop) +
  tm_raster(col.scale = tm_scale_continuous(values = 'inferno'),
            col.legend = tm_legend(title = 'Night light\nintensity',
                                   position = tm_pos_out('right'))) +
  tm_title('Houston Night Lights\nFebruary 07, 2021 (Before storm)',
           size = 0.8) +
  tm_compass(position = c('left', 'bottom'),
             size = 1,
             text.size = 0.6,
             color.dark = 'lemonchiffon3',
             text.color = 'ivory') +  
  tm_scalebar(position = c('left', 'bottom'),
              text.size = 0.8,
              color.dark = 'lemonchiffon3',
              text.color = 'ivory') +  
  tm_layout(bg.color = 'white',           
            outer.bg.color = 'white',      
            frame = FALSE)                  

beforestorm
```


```{r fig.width=12, fig.height=5}
# Map for February 16 (after storm)
afterstorm <- tm_shape(nightlight_16_crop) +
  tm_raster(col.scale = tm_scale_continuous(values = 'inferno'),
            col.legend = tm_legend(title = 'Night light\nintensity',
                                   position = tm_pos_out('right'))) +
  tm_title('Houston Night Lights\nFebruary 07, 2021 (After storm)',
           size = 0.8) +
  tm_compass(position = c('left', 'bottom'),
             size = 1,
             text.size = 0.6,
             color.dark = 'lemonchiffon3',
             text.color = 'ivory') +  
  tm_scalebar(position = c('left', 'bottom'),
              text.size = 0.8,
              color.dark = 'lemonchiffon3',
              text.color = 'ivory') +  
  tm_layout(bg.color = 'white',           
            outer.bg.color = 'white',      
            frame = FALSE) 

afterstorm
```


```{r fig.width=12, fig.height=5}
#| label: figure-beforeandafterstorm
tmap_arrange(beforestorm, afterstorm, ncol = 2)
```
```{r}

# Calculate the difference in light intensity
nightlight_diff <- nightlight_07 - nightlight_16

# Create houston blackout mask
nightlight_diff[nightlight_diff > 200] <- NA

# Change into vector 
blackout <- st_as_sf(nightlight_diff) %>% 
  st_make_valid() -m ""
```


